# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001


### GET Person by ID
GET {{Web_HostAddress}}/person?id=1

###

### POST Create Person
POST {{Web_HostAddress}}/person
Content-Type: application/json

// CreatePersonCommand
{
  "fullName": "John Doe",
  "addresses": [
    { "type": 1, "addressLine": "123 Main St" }
  ]
}

