version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: contactbook-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contactbookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ASP.NET Core Web API
  api:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: contactbook-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=contactbookdb;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres-data: